platform :ios, '5.0'
pod 'AFNetworking', '1.0'
pod 'Base64'
pod 'YRDropdownView', :git => 'https://github.com/iOctocat/YRDropdownView.git'
pod 'ECSlidingViewController', :git => 'https://github.com/iOctocat/ECSlidingViewController.git'
